# This is a basic workflow to help you get started with Actions

name: Comunicador de la legion


on:
  workflow_dispatch:
    inputs:
      villano:
        description: "¿Que villano quieres que transmita el mensaje?"
        required: true
        type: choice
        options:
          - "Lex Luthor"
          - "Thanos"
          - "Magneto"
          - "Brainiac"
          - "Joker"
      mensaje:
        description: "Mensaje para el consejo de villanos"
        required: true
        default: "La mision fue un exito, el mundo es nuestro"


      prioridad:
        description: "Nivel de prioridad del mensaje"
        required: true
        type: choice
        options:
          - 🟢 Normal
          - 🟡 Alta
          - 🔴 Urgente  
jobs:

  transmitir-mensaje:  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
