name: Reclutamiento de Agente

on: 
   workflow_dispatch:

jobs:
    reporte-de-reclutamiento: 
        runs-on: ubuntu-latest
        steps: 
            - name: El agente se presenta
              run: echo "Hola, soy Lex Luthor y soy el lider de la legion de supervillanos"

            - name: Reporte de identidad
              run: |
                echo "Reporte de identidad"
                echo "=============="
                echo ""
                echo "Nombre clave: ${{ github.actor }}"
                echo ""
                echo "Contexto de GitHub"
                echo "Repo: ${{ github.repository }}"
                echo "Operacion: ${{ github.sha }}"
                echo "Metadata: ${{ toJson(github) }}"

            - name: Capacidades del agente
              run: |
                echo "Capacidades detectadad"
                echo "Sistema Operativo"
                uname -a
                echo "Habilidades tecnicas"
                node --version
                git --version
                python3 --version

            - name: Reconocimiento del terreno
              run: |
                echo "Reconocimiento del terreno"
                ls /
                
